name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: ubuntu24.04
            arch: x86_64
            runs-on: ubuntu-latest
          - tag: ubuntu24.04
            arch: aarch64
            runs-on: ubuntu-24.04-arm
          - tag: ubuntu22.04
            arch: x86_64
            runs-on: ubuntu-latest
          - tag: ubuntu22.04
            arch: aarch64
            runs-on: ubuntu-24.04-arm
          - tag: ubuntu20.04
            arch: x86_64
            runs-on: ubuntu-latest
          - tag: ubuntu18.04
            arch: x86_64
            runs-on: ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          build-args: BASE_IMAGE=homebrew/${{ matrix.tag }}:latest
          outputs: type=image,name=zhongruoyu/homebrew-test-env,name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP"/digests/"$TAG-$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          TAG: ${{ matrix.tag }}
          ARCH: ${{ matrix.arch }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.tag }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  merge:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - primary-tag: ubuntu24.04
            tags: ubuntu24.04 noble
          - primary-tag: ubuntu22.04
            tags: ubuntu22.04 jammy latest
          - primary-tag: ubuntu20.04
            tags: ubuntu20.04 focal
          - primary-tag: ubuntu18.04
            tags: ubuntu18.04 bionic
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.primary-tag }}-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          tags=()
          for tag in $TAGS; do
            tags+=("--tag=zhongruoyu/homebrew-test-env:$tag")
          done

          images=()
          for digest in "$RUNNER_TEMP"/digests/"$PRIMARY_TAG"-*; do
            images+=("zhongruoyu/homebrew-test-env@sha256:$(cat "$digest")")
          done

          docker buildx imagetools create "${tags[@]}" "${images[@]}"
        env:
          PRIMARY_TAG: ${{ matrix.primary-tag }}
          TAGS: ${{ matrix.tags }}
