name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - primary-tag: ubuntu24.04-latest
            base-image: ghcr.io/homebrew/ubuntu24.04:latest
            tags: |
              ubuntu24.04-latest
              noble
            arches: x86_64 aarch64
          - primary-tag: ubuntu24.04-main
            base-image: ghcr.io/homebrew/ubuntu24.04:main
            tags: |
              ubuntu24.04-main
              noble-main
            arches: x86_64 aarch64
          - primary-tag: ubuntu22.04-latest
            base-image: ghcr.io/homebrew/ubuntu22.04:latest
            tags: |
              ubuntu22.04-latest
              jammy
              latest
            arches: x86_64 aarch64
          - primary-tag: ubuntu22.04-main
            base-image: ghcr.io/homebrew/ubuntu22.04:main
            tags: |
              ubuntu22.04-main
              jammy-main
              main
            arches: x86_64 aarch64
          - primary-tag: ubuntu20.04-latest
            base-image: ghcr.io/homebrew/ubuntu20.04:latest
            tags: |
              ubuntu20.04-latest
              focal
            arches: x86_64
    name: Build - ${{ matrix.primary-tag }}
    uses: ./.github/workflows/docker-build.yml
    with:
      primary-tag: ${{ matrix.primary-tag }}
      base-image: ${{ matrix.base-image }}
      tags: ${{ matrix.tags }}
      arches: ${{ matrix.arches }}
      push: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
