name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        target:
          - tags: zhongruoyu/homebrew-test-env:ubuntu22.04,zhongruoyu/homebrew-test-env:latest
            base-image: homebrew/ubuntu22.04
          - tags: zhongruoyu/homebrew-test-env:ubuntu20.04
            base-image: homebrew/ubuntu20.04
          - tags: zhongruoyu/homebrew-test-env:ubuntu18.04
            base-image: homebrew/ubuntu18.04
          - tags: zhongruoyu/homebrew-test-env:ubuntu16.04
            base-image: homebrew/ubuntu16.04
    env:
      REMOTE: ZhongRuoyu
      REMOTE_URL: https://github.com/ZhongRuoyu/homebrew-core.git
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.target.tags }}
          file: ${{ matrix.target.file }}
          build-args: |
            BASE_IMAGE=${{ matrix.target.base-image }}
            REMOTE=${{ env.REMOTE }}
            REMOTE_URL=${{ env.REMOTE_URL }}
          push: true
